from pathlib import Path
import subprocess

p = Path('index.html')
s = p.read_text()

def repl(old, new, label):
    global s
    n = s.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1 match, found {n}')
    s = s.replace(old, new, 1)

repl(
    "enemyRole='ROOKIE',killSlow=0;const keys={},tracers=[],combatFX=[];",
    "enemyRole='ROOKIE',killSlow=0,enemyAttackState=0,enemyAttackTimer=0,enemyBurstClock=0,enemyBurstShots=0,enemyTailTimer=0,enemyCounter=0,playerHP=3,playerInvuln=0,hostileNearCooldown=0;const keys={},tracers=[],combatFX=[];",
    'enemy fire state')

repl(
    "function crashNow(){if(crashed)return;crashed=true;silence();crashUI.style.display='grid';flashScreen(.45)}",
    "function crashNow(reason='IMPACT'){if(crashed)return;crashed=true;cancelEnemyAttack(99);silence();crashUI.innerHTML=`${reason}<small>PRESS R TO FLY AGAIN</small>`;crashUI.style.display='grid';flashScreen(.45)}",
    'crash reason')

repl(
    "tracers.push({mesh:bolt,velocity:dir.multiplyScalar(640+speed*.3),age:0,life:.85,salvo});",
    "tracers.push({mesh:bolt,velocity:dir.multiplyScalar(640+speed*.3),age:0,life:.85,salvo,friendly:true,near:false});",
    'friendly tracer tag')

fire_gun = "function fireGun(){if(crashed||missionComplete||missionCompleteTimer>0)return;gunSalvo++;makeTracer(-1,gunSalvo);makeTracer(1,gunSalvo);gunKick=Math.min(1,gunKick+.65);flashScreen(.035);chirp(175,.035,.03);chirp(88,.05,.02,.006)}"
enemy_fire = r"""function makeEnemyTracer(){if(!enemyAlive||crashed)return;const forward=new THREE.Vector3(0,0,-1).applyQuaternion(enemy.quaternion).normalize(),start=enemy.position.clone().addScaledVector(forward,4.8),range=start.distanceTo(ship.position),shipForward=new THREE.Vector3(0,0,-1).applyQuaternion(ship.quaternion).normalize(),lead=ship.position.clone().addScaledVector(shipForward,speed*(range/540)*.56),right=new THREE.Vector3().crossVectors(forward,worldUp).normalize(),up=new THREE.Vector3().crossVectors(right,forward).normalize(),nearBias=Math.random()<.72,sideError=nearBias?(Math.random()<.5?-1:1)*(6+Math.random()*(enemyRole==='ACE'?8:11)):(Math.random()-.5)*4,verticalError=(Math.random()-.5)*(nearBias?8:4);lead.addScaledVector(right,sideError).addScaledVector(up,verticalError);const dir=lead.sub(start).normalize(),material=new THREE.MeshBasicMaterial({color:0xff6545,transparent:true,opacity:.95,blending:THREE.AdditiveBlending,depthWrite:false}),bolt=new THREE.Mesh(new THREE.SphereGeometry(.42,8,6),material);bolt.scale.set(.55,.55,4.2);bolt.position.copy(start);bolt.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),dir);scene.add(bolt);tracers.push({mesh:bolt,velocity:dir.multiplyScalar(enemyRole==='ACE'?565:530),age:0,life:1.15,salvo:0,friendly:false,near:false});chirp(146,.028,.012)}
function enemyLOS(){const a=enemy.position,b=ship.position,dx=b.x-a.x,dz=b.z-a.z,len2=dx*dx+dz*dz;for(let i=1;i<=5;i++){const t=i/6,x=THREE.MathUtils.lerp(a.x,b.x,t),y=THREE.MathUtils.lerp(a.y,b.y,t),z=THREE.MathUtils.lerp(a.z,b.z,t);if(y<terrainHeight(x,z)+10)return false}for(const m of scenery){if(!m.visible||!m.userData.collisionR)continue;const u=THREE.MathUtils.clamp(((m.position.x-a.x)*dx+(m.position.z-a.z)*dz)/Math.max(len2,.001),0,1);if(u<=.04||u>=.96)continue;const x=a.x+dx*u,z=a.z+dz*u,r=(m.userData.collisionR||0)+5;if((x-m.position.x)**2+(z-m.position.z)**2>r*r)continue;const y=THREE.MathUtils.lerp(a.y,b.y,u);if(Math.abs(y-m.position.y)<(m.userData.collisionH||8)+10)return false}return true}
function enemyFireSolution(){if(!enemyAlive||crashed||missionComplete||missionCompleteTimer>0||enemyTime<1.25||(enemyRole!=='CLIMBER'&&enemyRole!=='ACE'))return false;const toShip=ship.position.clone().sub(enemy.position),range=toShip.length();if(range<(enemyRole==='ACE'?72:82)||range>(enemyRole==='ACE'?520:440))return false;const forward=new THREE.Vector3(0,0,-1).applyQuaternion(enemy.quaternion).normalize(),aim=toShip.multiplyScalar(1/Math.max(range,.001));if(forward.dot(aim)<(enemyRole==='ACE'?.91:.94))return false;return enemyLOS()}
function resetEnemyAttack(delay=1.4){enemyAttackState=3;enemyAttackTimer=delay;enemyBurstClock=0;enemyBurstShots=0}
function cancelEnemyAttack(delay=.85){enemyAttackState=3;enemyAttackTimer=delay;enemyBurstClock=0;enemyBurstShots=0}
function hostileNearMiss(){if(hostileNearCooldown>0||crashed)return;hostileNearCooldown=.22;hitKick=Math.max(hitKick,.3);flashScreen(.035);chirp(96,.045,.025);chirp(1180,.028,.018,.006)}
function hitPlayer(){if(playerInvuln>0||crashed)return;playerHP--;playerInvuln=1.25;hitKick=Math.max(hitKick,.86);flashScreen(.27);chirp(68,.12,.055);chirp(230,.085,.034,.018);if(playerHP<=0){announce('AIRFRAME FAILURE');crashNow('SHOT DOWN')}else announce(playerHP===1?'AIRFRAME CRITICAL':'AIRFRAME HIT')}
function updateEnemyAttack(dt){playerInvuln=Math.max(0,playerInvuln-dt);hostileNearCooldown=Math.max(0,hostileNearCooldown-dt);const eligible=enemyAlive&&!crashed&&!missionComplete&&missionCompleteTimer<=0&&(enemyRole==='CLIMBER'||enemyRole==='ACE');if(!eligible){if(enemyAttackState===1||enemyAttackState===2)cancelEnemyAttack(1);return}if(enemyAttackState===3){enemyAttackTimer-=dt;if(enemyAttackTimer<=0)enemyAttackState=0;return}const solution=enemyFireSolution();if(enemyAttackState===0){if(solution){enemyAttackState=1;enemyAttackTimer=enemyRole==='ACE'?.32:.42;hitKick=Math.max(hitKick,.08);chirp(310,.055,.026);chirp(860,.055,.024,.16)}return}if(!solution){cancelEnemyAttack(.75);return}if(enemyAttackState===1){enemyAttackTimer-=dt;if(enemyAttackTimer<=0){enemyAttackState=2;enemyBurstClock=0;enemyBurstShots=0;chirp(1320,.04,.027)}return}if(enemyAttackState===2){enemyBurstClock-=dt;const maxShots=enemyRole==='ACE'?4:3,spacing=enemyRole==='ACE'?.095:.115;if(enemyBurstShots<maxShots&&enemyBurstClock<=0){makeEnemyTracer();enemyBurstShots++;enemyBurstClock=spacing}if(enemyBurstShots>=maxShots&&enemyBurstClock<=0){enemyAttackState=3;enemyAttackTimer=enemyRole==='ACE'?2.65:3.35}}}"""
repl(fire_gun, fire_gun + '\n' + enemy_fire, 'enemy fire functions')

repl(
    "enemyAlive=false;enemy.visible=false;spawnKillDebris(deathPos,deathVel);",
    "enemyAlive=false;enemy.visible=false;cancelEnemyAttack(.9);spawnKillDebris(deathPos,deathVel);",
    'cancel attack on kill')

repl(
    "closureFps=0;announce(firstTarget&&!worldIndex?'BANDIT AHEAD':`${enemyRole} INBOUND`)}",
    "closureFps=0;enemyTailTimer=enemyCounter=0;resetEnemyAttack(enemyRole==='ACE'?1.05:enemyRole==='CLIMBER'?1.45:99);announce(firstTarget&&!worldIndex?'BANDIT AHEAD':`${enemyRole} INBOUND`)}",
    'spawn attack reset')

old_enemy = "function updateEnemy(dt){if(!enemyAlive){if(kills>=MISSION_KILLS)return;respawn-=dt;if(respawn<=0)spawnEnemy(false);return}lastEnemy.copy(enemy.position);enemyTime+=dt;const role=enemyRole,range=enemy.position.distanceTo(ship.position),r=new THREE.Vector3().crossVectors(enemyCourse,worldUp).normalize(),weaveFreq=role==='ROOKIE'?.7:role==='SKIMMER'?1.35:role==='CLIMBER'?.95:1.55,weaveAmp=role==='ROOKIE'?.045:role==='SKIMMER'?.28:role==='CLIMBER'?.16:.36,weave=Math.sin(enemyTime*weaveFreq)*weaveAmp,clearance=role==='SKIMMER'?(worldIndex?50:40):role==='CLIMBER'?(worldIndex?108:88):role==='ACE'?(worldIndex?82:68):(worldIndex?68:54),desiredAlt=terrainHeight(enemy.position.x,enemy.position.z)+clearance,altBias=THREE.MathUtils.clamp((desiredAlt-enemy.position.y)/170,-.15,.18),roleClimb=role==='CLIMBER'?Math.sin(enemyTime*.9)*.15:role==='ACE'?Math.sin(enemyTime*1.4)*.09:Math.sin(enemyTime*.7)*(firstTarget?.02:.045),climb=roleClimb+altBias,dir=steerAroundObstacles(enemy.position,enemyCourse.clone().addScaledVector(r,weave).addScaledVector(worldUp,climb).normalize()),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),dir),turnRate=role==='ROOKIE'?.65:role==='SKIMMER'?1.08:role==='CLIMBER'?1.18:1.38;enemy.quaternion.slerp(q,1-Math.exp(-dt*turnRate));const base=role==='ROOKIE'?108:role==='SKIMMER'?116:role==='CLIMBER'?120:126,escape=range<52?(52-range)*.38:0,cap=role==='ROOKIE'?122:role==='SKIMMER'?128:role==='CLIMBER'?132:136,enemySpeed=Math.min(base+escape+(firstTarget?0:kills*1.5),cap);enemy.position.addScaledVector(new THREE.Vector3(0,0,-1).applyQuaternion(enemy.quaternion),enemySpeed*dt);const floor=terrainHeight(enemy.position.x,enemy.position.z)+16;if(enemy.position.y<floor)enemy.position.y=THREE.MathUtils.lerp(enemy.position.y,floor,1-Math.exp(-dt/.16));separateEnemyFromObstacles();enemyVel.copy(enemy.position).sub(lastEnemy).divideScalar(Math.max(dt,.001))}"
new_enemy = "function updateEnemy(dt){if(!enemyAlive){if(kills>=MISSION_KILLS)return;respawn-=dt;if(respawn<=0)spawnEnemy(false);return}lastEnemy.copy(enemy.position);enemyTime+=dt;const role=enemyRole,range=enemy.position.distanceTo(ship.position),enemyForward=new THREE.Vector3(0,0,-1).applyQuaternion(enemy.quaternion).normalize(),toPlayer=ship.position.clone().sub(enemy.position),toPlayerDir=toPlayer.lengthSq()>.001?toPlayer.normalize():enemyForward.clone(),playerBehind=enemyForward.dot(toPlayerDir)<-.38&&range<320;if((role==='CLIMBER'||role==='ACE')&&playerBehind&&enemyCounter<=0){enemyTailTimer+=dt;if(enemyTailTimer>(role==='ACE'?.75:1.05)){enemyCounter=role==='ACE'?1.45:1.15;enemyTailTimer=0}}else enemyTailTimer=Math.max(0,enemyTailTimer-dt*1.8);enemyCounter=Math.max(0,enemyCounter-dt);const r=new THREE.Vector3().crossVectors(enemyForward,worldUp).normalize(),weaveFreq=role==='ROOKIE'?.7:role==='SKIMMER'?1.35:role==='CLIMBER'?.95:1.55,weaveAmp=role==='ROOKIE'?.045:role==='SKIMMER'?.28:role==='CLIMBER'?.16:.36,weave=Math.sin(enemyTime*weaveFreq)*weaveAmp,clearance=role==='SKIMMER'?(worldIndex?50:40):role==='CLIMBER'?(worldIndex?108:88):role==='ACE'?(worldIndex?82:68):(worldIndex?68:54),desiredAlt=terrainHeight(enemy.position.x,enemy.position.z)+clearance,altBias=THREE.MathUtils.clamp((desiredAlt-enemy.position.y)/170,-.15,.18),roleClimb=role==='CLIMBER'?Math.sin(enemyTime*.9)*.15:role==='ACE'?Math.sin(enemyTime*1.4)*.09:Math.sin(enemyTime*.7)*(firstTarget?.02:.045),climb=roleClimb+altBias,intent=enemyCourse.clone().addScaledVector(r,weave).addScaledVector(worldUp,climb).normalize();if(enemyCounter>0){const breakSide=Math.sin(enemyTime*3.2)>=0?1:-1;intent.lerp(toPlayerDir,role==='ACE'?.82:.7).addScaledVector(r,breakSide*(role==='ACE'?.2:.14)).addScaledVector(worldUp,role==='CLIMBER'?.12:.06).normalize()}const dir=steerAroundObstacles(enemy.position,intent),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),dir),baseTurn=role==='ROOKIE'?.65:role==='SKIMMER'?1.08:role==='CLIMBER'?1.18:1.38,turnRate=baseTurn+(enemyCounter>0?(role==='ACE'?1.35:.9):0);enemy.quaternion.slerp(q,1-Math.exp(-dt*turnRate));const base=role==='ROOKIE'?108:role==='SKIMMER'?116:role==='CLIMBER'?120:126,escape=range<52?(52-range)*.38:0,cap=role==='ROOKIE'?122:role==='SKIMMER'?128:role==='CLIMBER'?132:136,enemySpeed=Math.min(base+escape+(firstTarget?0:kills*1.5),cap);enemy.position.addScaledVector(new THREE.Vector3(0,0,-1).applyQuaternion(enemy.quaternion),enemySpeed*dt);const floor=terrainHeight(enemy.position.x,enemy.position.z)+16;if(enemy.position.y<floor)enemy.position.y=THREE.MathUtils.lerp(enemy.position.y,floor,1-Math.exp(-dt/.16));separateEnemyFromObstacles();enemyVel.copy(enemy.position).sub(lastEnemy).divideScalar(Math.max(dt,.001))}"
repl(old_enemy, new_enemy, 'counter maneuver AI')

old_weapons = "function updateWeapons(dt){missileRearm=Math.max(0,missileRearm-dt);gunClock-=dt;if(keys.Space&&gunClock<=0){fireGun();gunClock=.09}for(let i=tracers.length-1;i>=0;i--){const t=tracers[i],previous=t.mesh.position.clone();t.age+=dt;t.mesh.position.addScaledVector(t.velocity,dt);t.mesh.material.opacity=THREE.MathUtils.clamp((t.life-t.age)/.12,0,1);const travel=t.mesh.position.clone().sub(previous),toEnemy=enemyAlive?enemy.position.clone().sub(previous):null,u=toEnemy?THREE.MathUtils.clamp(toEnemy.dot(travel)/Math.max(travel.lengthSq(),.001),0,1):0,hit=enemyAlive&&previous.addScaledVector(travel,u).distanceToSquared(enemy.position)<36,expired=t.age>=t.life||t.mesh.position.y<terrainHeight(t.mesh.position.x,t.mesh.position.z);if(hit||expired){scene.remove(t.mesh);t.mesh.geometry.dispose();t.mesh.material.dispose();tracers.splice(i,1)}if(hit&&t.salvo!==lastGunHit){lastGunHit=t.salvo;enemyHP--;const lethal=enemyHP<=0;spawnImpactFX(enemy.position.clone(),lethal);flashScreen(lethal?.15:.065);announce(lethal?'GUN KILL':'HIT');if(lethal)explode()}}if(!missile)return;missile.life-=dt;missile.age+=dt;missile.trailClock-=dt;if(!missile.ignited&&missile.age>=missile.igniteAt){missile.ignited=true;missile.flame.visible=true;missile.v.normalize().multiplyScalar(232);chirp(520,.045,.032);chirp(94,.07,.03,.004)}if(missile.ignited&&missile.trailClock<=0){spawnMissileTrail(missile.mesh.position,missile.v);missile.trailClock=.026}const missilePrevious=missile.mesh.position.clone();if(enemyAlive&&missile.guided&&missile.ignited){const desired=enemy.position.clone().addScaledVector(enemyVel,.14).sub(missile.mesh.position).normalize().multiplyScalar(294),turn=1-Math.exp(-dt*4.8);missile.v.lerp(desired,turn);missile.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),missile.v.clone().normalize())}missile.mesh.position.addScaledVector(missile.v,dt);const missileTravel=missile.mesh.position.clone().sub(missilePrevious),missileToEnemy=enemyAlive?enemy.position.clone().sub(missilePrevious):null,missileU=missileToEnemy?THREE.MathUtils.clamp(missileToEnemy.dot(missileTravel)/Math.max(missileTravel.lengthSq(),.001),0,1):0;if(enemyAlive&&missilePrevious.addScaledVector(missileTravel,missileU).distanceToSquared(enemy.position)<81){removeMissile();enemyHP-=4;const lethal=enemyHP<=0;spawnImpactFX(enemy.position.clone(),lethal,false);hitKick=Math.min(1,hitKick+.58);flashScreen(lethal?.23:.12);chirp(72,.115,.05);chirp(390,.06,.032,.012);announce(lethal?'MISSILE KILL':'MISSILE HIT');if(lethal)explode();else{lockState=lockTimer=lastLock=0;silence()}return}if(missile.life<=0)removeMissile()}"
new_weapons = "function updateWeapons(dt){missileRearm=Math.max(0,missileRearm-dt);gunClock-=dt;if(keys.Space&&gunClock<=0){fireGun();gunClock=.09}for(let i=tracers.length-1;i>=0;i--){const t=tracers[i],previous=t.mesh.position.clone();t.age+=dt;t.mesh.position.addScaledVector(t.velocity,dt);t.mesh.material.opacity=THREE.MathUtils.clamp((t.life-t.age)/.12,0,1);const travel=t.mesh.position.clone().sub(previous),targetPos=t.friendly===false?ship.position:(enemyAlive?enemy.position:null),toTarget=targetPos?targetPos.clone().sub(previous):null,u=toTarget?THREE.MathUtils.clamp(toTarget.dot(travel)/Math.max(travel.lengthSq(),.001),0,1):0,closest=previous.clone().addScaledVector(travel,u),d2=targetPos?closest.distanceToSquared(targetPos):Infinity,friendlyHit=t.friendly!==false&&enemyAlive&&d2<36,hostileHit=t.friendly===false&&!crashed&&playerInvuln<=0&&d2<25,hostileNear=t.friendly===false&&!t.near&&d2<225&&!hostileHit,expired=t.age>=t.life||t.mesh.position.y<terrainHeight(t.mesh.position.x,t.mesh.position.z);if(hostileNear){t.near=true;hostileNearMiss()}if(friendlyHit||hostileHit||expired){scene.remove(t.mesh);t.mesh.geometry.dispose();t.mesh.material.dispose();tracers.splice(i,1)}if(friendlyHit&&t.salvo!==lastGunHit){lastGunHit=t.salvo;enemyHP--;const lethal=enemyHP<=0;spawnImpactFX(enemy.position.clone(),lethal);flashScreen(lethal?.15:.065);announce(lethal?'GUN KILL':'HIT');if(lethal)explode()}if(hostileHit)hitPlayer()}if(!missile)return;missile.life-=dt;missile.age+=dt;missile.trailClock-=dt;if(!missile.ignited&&missile.age>=missile.igniteAt){missile.ignited=true;missile.flame.visible=true;missile.v.normalize().multiplyScalar(232);chirp(520,.045,.032);chirp(94,.07,.03,.004)}if(missile.ignited&&missile.trailClock<=0){spawnMissileTrail(missile.mesh.position,missile.v);missile.trailClock=.026}const missilePrevious=missile.mesh.position.clone();if(enemyAlive&&missile.guided&&missile.ignited){const desired=enemy.position.clone().addScaledVector(enemyVel,.14).sub(missile.mesh.position).normalize().multiplyScalar(294),turn=1-Math.exp(-dt*4.8);missile.v.lerp(desired,turn);missile.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),missile.v.clone().normalize())}missile.mesh.position.addScaledVector(missile.v,dt);const missileTravel=missile.mesh.position.clone().sub(missilePrevious),missileToEnemy=enemyAlive?enemy.position.clone().sub(missilePrevious):null,missileU=missileToEnemy?THREE.MathUtils.clamp(missileToEnemy.dot(missileTravel)/Math.max(missileTravel.lengthSq(),.001),0,1):0;if(enemyAlive&&missilePrevious.addScaledVector(missileTravel,missileU).distanceToSquared(enemy.position)<81){removeMissile();enemyHP-=4;const lethal=enemyHP<=0;spawnImpactFX(enemy.position.clone(),lethal,false);hitKick=Math.min(1,hitKick+.58);flashScreen(lethal?.23:.12);chirp(72,.115,.05);chirp(390,.06,.032,.012);announce(lethal?'MISSILE KILL':'MISSILE HIT');if(lethal)explode();else{lockState=lockTimer=lastLock=0;silence()}return}if(missile.life<=0)removeMissile()}"
repl(old_weapons, new_weapons, 'owner-aware weapon loop')

repl(
    "missileRearm=0;killSlow=0;enemyRole='SKIMMER';dangerCooldown=0;",
    "missileRearm=0;killSlow=0;enemyRole='SKIMMER';playerHP=3;playerInvuln=hostileNearCooldown=0;enemyAttackState=enemyAttackTimer=enemyBurstClock=enemyBurstShots=enemyTailTimer=enemyCounter=0;dangerCooldown=0;",
    'alpine player threat reset')

repl(
    "missionElapsed=citySplit=finalTime=0;killSlow=0;enemyRole='ROOKIE';setWorldTheme(false);",
    "missionElapsed=citySplit=finalTime=0;killSlow=0;enemyRole='ROOKIE';playerHP=3;playerInvuln=hostileNearCooldown=0;enemyAttackState=enemyAttackTimer=enemyBurstClock=enemyBurstShots=enemyTailTimer=enemyCounter=0;setWorldTheme(false);",
    'full reset player threat')

repl(
    "updateWorld();updateEnemy(dt);updateMission(dt);",
    "updateWorld();updateEnemy(dt);updateEnemyAttack(dt);updateMission(dt);",
    'attack update loop')

p.write_text(s)
script_start = s.index('<script type="module">') + len('<script type="module">')
script_end = s.index('</script>', script_start)
check = Path('/tmp/emberwing.mjs')
check.write_text(s[script_start:script_end])
subprocess.run(['node', '--check', str(check)], check=True)
subprocess.run(['git', 'diff', '--check'], check=True)
print('monk patch applied and syntax checked')
