from pathlib import Path
import subprocess

p=Path('index.html')
s=p.read_text()
old="function updateFlight(dt){if(crashed||missionComplete||missionCompleteTimer>0)return;turboBurst=Math.max(0,turboBurst-dt);const pi=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),ri=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),ab=keys.ShiftLeft||keys.ShiftRight||turboBurst>0,range=enemyAlive?enemy.position.distanceTo(ship.position):999,closeFactor=enemyAlive?THREE.MathUtils.clamp((range-42)/115,.18,1):1;burner=THREE.MathUtils.lerp(burner,ab?1:0,1-Math.exp(-dt/(ab?.1:.2)));speed=THREE.MathUtils.lerp(speed,124+burner*56*closeFactor,1-Math.exp(-dt/.14));burnerUI.className=burner>.35?'on':'';const engineFlicker=1+Math.sin(performance.now()*.027)*.045+Math.sin(performance.now()*.061)*.018;for(const e of ship.userData.engines){e.scale.setScalar(.94+burner*.34+engineFlicker*.045);e.material.opacity=.78+burner*.2;e.material.color.setRGB(1,.47+burner*.14,.16+burner*.05)}for(const p of ship.userData.plumes){p.scale.z=(1.05+burner*1.95)*engineFlicker;p.material.opacity=.66+burner*.32}pitchRate=THREE.MathUtils.lerp(pitchRate,pi*1.08,1-Math.exp(-dt/.17));rollRate=THREE.MathUtils.lerp(rollRate,ri*2.2,1-Math.exp(-dt/.09));ship.rotateX(pitchRate*dt);ship.rotateZ(-rollRate*dt);tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();const up=worldUp.clone().applyQuaternion(ship.quaternion),bank=Math.atan2(up.x,up.y),combatPull=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(bank),.46,.98),turnAssist=(bank*.72+ri*.18)*(1+combatPull*.3);if(combatPull>.001)ship.rotateX(pitchRate*dt*combatPull*.14);if(!ri)ship.rotateZ(bank*.62*dt);if(!pi)ship.rotateX(-tmpF.y*.3*dt);ship.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(worldUp,-turnAssist*dt));tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();ship.position.addScaledVector(tmpF,speed*dt);worldTravel+=speed*dt;const floor=terrainHeight(ship.position.x,ship.position.z)+3;if(ship.position.y<floor){ship.position.y=floor;crashNow();return}checkObstacleCollision()}"
new="function updateFlight(dt){if(crashed||missionComplete||missionCompleteTimer>0)return;turboBurst=Math.max(0,turboBurst-dt);const pi=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),ri=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),ab=keys.ShiftLeft||keys.ShiftRight||turboBurst>0,range=enemyAlive?enemy.position.distanceTo(ship.position):999,closeFactor=enemyAlive?THREE.MathUtils.clamp((range-42)/115,.18,1):1;burner=THREE.MathUtils.lerp(burner,ab?1:0,1-Math.exp(-dt/(ab?.1:.2)));const preUp=worldUp.clone().applyQuaternion(ship.quaternion),preBank=Math.atan2(preUp.x,preUp.y),pullDemand=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(preBank),.28,.82),targetSpeed=124-pullDemand*10+burner*56*closeFactor;speed=THREE.MathUtils.lerp(speed,targetSpeed,1-Math.exp(-dt/.14));burnerUI.className=burner>.35?'on':'';const engineFlicker=1+Math.sin(performance.now()*.027)*.045+Math.sin(performance.now()*.061)*.018;for(const e of ship.userData.engines){e.scale.setScalar(.94+burner*.34+engineFlicker*.045);e.material.opacity=.78+burner*.2;e.material.color.setRGB(1,.47+burner*.14,.16+burner*.05)}for(const p of ship.userData.plumes){p.scale.z=(1.05+burner*1.95)*engineFlicker;p.material.opacity=.66+burner*.32}pitchRate=THREE.MathUtils.lerp(pitchRate,pi*(1.08+pullDemand*.34),1-Math.exp(-dt/(pullDemand>.1?.12:.17)));rollRate=THREE.MathUtils.lerp(rollRate,ri*2.2,1-Math.exp(-dt/.09));ship.rotateX(pitchRate*dt);ship.rotateZ(-rollRate*dt);tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();const up=worldUp.clone().applyQuaternion(ship.quaternion),bank=Math.atan2(up.x,up.y),combatPull=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(bank),.28,.82),turnAssist=(bank*.72+ri*.18)*(1+combatPull*.58);if(combatPull>.001)ship.rotateX(pitchRate*dt*combatPull*.18);if(!ri)ship.rotateZ(bank*.62*dt);if(!pi)ship.rotateX(-tmpF.y*.3*dt);ship.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(worldUp,-turnAssist*dt));tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();ship.position.addScaledVector(tmpF,speed*dt);worldTravel+=speed*dt;const floor=terrainHeight(ship.position.x,ship.position.z)+3;if(ship.position.y<floor){ship.position.y=floor;crashNow();return}checkObstacleCollision()}"
if s.count(old)!=1:
    raise SystemExit(f'updateFlight match count {s.count(old)}')
s=s.replace(old,new,1)
p.write_text(s)
html=s[s.index('<script type="module">')+len('<script type="module">'):s.index('</script>')]
html=html.replace("import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';",'const THREE={};')
Path('/tmp/emberwing-check.mjs').write_text(html)
subprocess.run(['node','--check','/tmp/emberwing-check.mjs'],check=True)
