from pathlib import Path
import subprocess

p=Path('index.html')
s=p.read_text()

repls=[]
repls.append((
"#target.offscreen{width:48px;height:48px;box-shadow:0 0 28px #ffbf4f99}",
"#target.offscreen{width:48px;height:48px;box-shadow:0 0 28px #ffbf4f99}#target.offscreen:before{content:attr(data-stack);position:absolute;left:50%;top:-22px;transform:translateX(-50%) rotate(-45deg);font-size:13px;font-weight:900;color:#ffd879;text-shadow:0 0 10px #ff9b31aa}"
))

repls.append((
"function updateFlight(dt){if(crashed||missionComplete||missionCompleteTimer>0)return;turboBurst=Math.max(0,turboBurst-dt);const pi=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),ri=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),ab=keys.ShiftLeft||keys.ShiftRight||turboBurst>0,range=enemyAlive?enemy.position.distanceTo(ship.position):999,closeFactor=enemyAlive?THREE.MathUtils.clamp((range-42)/115,.18,1):1;burner=THREE.MathUtils.lerp(burner,ab?1:0,1-Math.exp(-dt/(ab?.1:.2)));const preUp=worldUp.clone().applyQuaternion(ship.quaternion),preBank=Math.atan2(preUp.x,preUp.y),pullDemand=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(preBank),.28,.82),targetSpeed=124-pullDemand*10+burner*56*closeFactor;speed=THREE.MathUtils.lerp(speed,targetSpeed,1-Math.exp(-dt/.14));burnerUI.className=burner>.35?'on':'';const engineFlicker=1+Math.sin(performance.now()*.027)*.045+Math.sin(performance.now()*.061)*.018;for(const e of ship.userData.engines){e.scale.setScalar(.94+burner*.34+engineFlicker*.045);e.material.opacity=.78+burner*.2;e.material.color.setRGB(1,.47+burner*.14,.16+burner*.05)}for(const p of ship.userData.plumes){p.scale.z=(1.05+burner*1.95)*engineFlicker;p.material.opacity=.66+burner*.32}pitchRate=THREE.MathUtils.lerp(pitchRate,pi*(1.08+pullDemand*.34),1-Math.exp(-dt/(pullDemand>.1?.12:.17)));rollRate=THREE.MathUtils.lerp(rollRate,ri*2.2,1-Math.exp(-dt/.09));ship.rotateX(pitchRate*dt);ship.rotateZ(-rollRate*dt);tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();const up=worldUp.clone().applyQuaternion(ship.quaternion),bank=Math.atan2(up.x,up.y),combatPull=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(bank),.28,.82),turnAssist=(bank*.72+ri*.18)*(1+combatPull*.58);if(combatPull>.001)ship.rotateX(pitchRate*dt*combatPull*.18);if(!ri)ship.rotateZ(bank*.62*dt);if(!pi)ship.rotateX(-tmpF.y*.3*dt);ship.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(worldUp,-turnAssist*dt));tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();ship.position.addScaledVector(tmpF,speed*dt);worldTravel+=speed*dt;const floor=terrainHeight(ship.position.x,ship.position.z)+3;if(ship.position.y<floor){ship.position.y=floor;crashNow();return}checkObstacleCollision()}",
"function updateFlight(dt){if(crashed||missionComplete||missionCompleteTimer>0)return;turboBurst=Math.max(0,turboBurst-dt);const pi=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),ri=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),ab=keys.ShiftLeft||keys.ShiftRight||turboBurst>0,range=enemyAlive?enemy.position.distanceTo(ship.position):999,closeFactor=enemyAlive?THREE.MathUtils.clamp((range-42)/115,.18,1):1;burner=THREE.MathUtils.lerp(burner,ab?1:0,1-Math.exp(-dt/(ab?.1:.2)));const preUp=worldUp.clone().applyQuaternion(ship.quaternion),preBank=Math.atan2(preUp.x,preUp.y),pullDemand=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(preBank),.26,.78),targetSpeed=124-pullDemand*14+burner*56*closeFactor;speed=THREE.MathUtils.lerp(speed,targetSpeed,1-Math.exp(-dt/.14));burnerUI.className=burner>.35?'on':'';const engineFlicker=1+Math.sin(performance.now()*.027)*.045+Math.sin(performance.now()*.061)*.018;for(const e of ship.userData.engines){e.scale.setScalar(.94+burner*.34+engineFlicker*.045);e.material.opacity=.78+burner*.2;e.material.color.setRGB(1,.47+burner*.14,.16+burner*.05)}for(const p of ship.userData.plumes){p.scale.z=(1.05+burner*1.95)*engineFlicker;p.material.opacity=.66+burner*.32}pitchRate=THREE.MathUtils.lerp(pitchRate,pi*(1.08+pullDemand*.42),1-Math.exp(-dt/(pullDemand>.1?.105:.17)));rollRate=THREE.MathUtils.lerp(rollRate,ri*2.2,1-Math.exp(-dt/.09));ship.rotateX(pitchRate*dt);ship.rotateZ(-rollRate*dt);tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();const up=worldUp.clone().applyQuaternion(ship.quaternion),bank=Math.atan2(up.x,up.y),combatPull=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(bank),.26,.78),turnAssist=(bank*.72+ri*.18)*(1+combatPull*.72);if(combatPull>.001)ship.rotateX(pitchRate*dt*combatPull*.22);if(!ri)ship.rotateZ(bank*.62*dt);if(!pi)ship.rotateX(-tmpF.y*.3*dt);ship.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(worldUp,-turnAssist*dt));tmpF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();ship.position.addScaledVector(tmpF,speed*dt);worldTravel+=speed*dt;const floor=terrainHeight(ship.position.x,ship.position.z)+3;if(ship.position.y<floor){ship.position.y=floor;crashNow();return}checkObstacleCollision()}"
))

repls.append((
"if(enemyCounter>0){const breakSide=Math.sin(enemyTime*3.2)>=0?1:-1;intent.lerp(toPlayerDir,role==='ACE'?.82:.7).addScaledVector(r,breakSide*(role==='ACE'?.2:.14)).addScaledVector(worldUp,role==='CLIMBER'?.12:.06).normalize()}const dir=steerAroundObstacles(enemy.position,intent),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),dir),baseTurn=role==='ROOKIE'?.65:role==='SKIMMER'?1.08:role==='CLIMBER'?1.18:1.38,turnRate=baseTurn+(enemyCounter>0?(role==='ACE'?1.08:.68):0);",
"if(enemyCounter>0){const breakSide=Math.sin(enemyTime*3.0)>=0?1:-1;if(role==='CLIMBER'){const vertical=Math.sin(enemyTime*2.8)*.34;intent.copy(enemyForward).addScaledVector(r,breakSide*.24).addScaledVector(worldUp,vertical+.08).normalize()}else{intent.copy(enemyForward).lerp(toPlayerDir,.36).addScaledVector(r,breakSide*.28).addScaledVector(worldUp,Math.sin(enemyTime*2.6)*.16).normalize()}}const dir=steerAroundObstacles(enemy.position,intent),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),dir),baseTurn=role==='ROOKIE'?.65:role==='SKIMMER'?1.08:role==='CLIMBER'?1.18:1.38,turnRate=baseTurn+(enemyCounter>0?(role==='ACE'?.68:.36):0);"
))

repls.append((
"function updateGuidance(){if(!enemyAlive){targetUI.style.opacity='0';return}const local=enemy.position.clone().sub(camera.position).applyQuaternion(camera.quaternion.clone().invert()),front=local.z<0,p=enemy.position.clone().project(camera),ons=front&&Math.abs(p.x)<.86&&Math.abs(p.y)<.76,margin=62;let x,y;if(ons){x=(p.x*.5+.5)*innerWidth;y=(-p.y*.5+.5)*innerHeight;if(Math.abs(local.x)>.25)guideSide=Math.sign(local.x)}else{if(Math.abs(local.x)>.4)guideSide=Math.sign(local.x);const az=Math.atan2(local.x,-local.z),flat=Math.max(1,Math.hypot(local.x,local.z));let dx=Math.sin(az),dy=-THREE.MathUtils.clamp(local.y/flat,-.9,.9);if(!front&&Math.abs(dx)<.055)dx=guideSide*.055;const mag=Math.max(.001,Math.hypot(dx,dy));dx/=mag;dy/=mag;const sc=Math.min((innerWidth/2-margin)/Math.max(.001,Math.abs(dx)),(innerHeight/2-margin)/Math.max(.001,Math.abs(dy)));x=innerWidth/2+dx*sc;y=innerHeight/2+dy*sc}const follow=ons?.5:.22;guideX=THREE.MathUtils.lerp(guideX,x,follow);guideY=THREE.MathUtils.lerp(guideY,y,follow);targetUI.style.left=guideX+'px';targetUI.style.top=guideY+'px';targetUI.style.opacity=lockState===2?'1':lockState===1?'.78':'.62';const ft=Math.max(0,Math.round(displayRangeFeet/5)*5),closing=closureFps>18?` ↓ ${Math.round(closureFps)} FT/S`:closureFps<-18?` ↑ ${Math.round(-closureFps)} FT/S`:'';targetUI.dataset.range=`${ft} FT${closing}`;targetUI.className=!ons?'offscreen':lockState===2?'lock':lockState===1?'track':''}",
"function updateGuidance(){if(!enemyAlive){targetUI.style.opacity='0';return}const local=enemy.position.clone().sub(camera.position).applyQuaternion(camera.quaternion.clone().invert()),front=local.z<0,p=enemy.position.clone().project(camera),ons=front&&Math.abs(p.x)<.86&&Math.abs(p.y)<.76,cx=innerWidth*.5,cy=innerHeight*.42;let x,y;if(ons){x=(p.x*.5+.5)*innerWidth;y=(-p.y*.5+.5)*innerHeight;if(Math.abs(local.x)>.25)guideSide=Math.sign(local.x);targetUI.dataset.stack=''}else{if(Math.abs(local.x)>.4)guideSide=Math.sign(local.x);const az=Math.atan2(local.x,-local.z),flat=Math.max(1,Math.hypot(local.x,local.z));let dx=Math.sin(az),dy=-THREE.MathUtils.clamp(local.y/flat,-.82,.82);if(!front&&Math.abs(dx)<.09)dx=guideSide*.09;const mag=Math.max(.001,Math.hypot(dx,dy));dx/=mag;dy/=mag;const radius=Math.min(innerWidth,innerHeight)*.3;x=cx+dx*radius;y=cy+dy*radius;targetUI.dataset.stack=local.y>flat*.11?'▲':local.y<-flat*.11?'▼':'·'}const follow=ons?.5:.28;guideX=THREE.MathUtils.lerp(guideX,x,follow);guideY=THREE.MathUtils.lerp(guideY,y,follow);targetUI.style.left=guideX+'px';targetUI.style.top=guideY+'px';targetUI.style.opacity=lockState===2?'1':lockState===1?'.78':'.68';const ft=Math.max(0,Math.round(displayRangeFeet/5)*5),closing=closureFps>18?` ↓ ${Math.round(closureFps)} FT/S`:closureFps<-18?` ↑ ${Math.round(-closureFps)} FT/S`:'';targetUI.dataset.range=`${ft} FT${closing}`;targetUI.className=!ons?'offscreen':lockState===2?'lock':lockState===1?'track':''}"
))

repls.append((
"const camF=new THREE.Vector3(),camPos=new THREE.Vector3(),look=new THREE.Vector3();function updateCamera(dt){gunKick*=Math.exp(-dt/.065);hitKick*=Math.exp(-dt/.075);camF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();const up=worldUp.clone().applyQuaternion(ship.quaternion),bank=Math.atan2(up.x,up.y),alt=Math.max(0,ship.position.y-terrainHeight(ship.position.x,ship.position.z)),velocity=THREE.MathUtils.clamp((speed-124)/56,0,1),lowAir=THREE.MathUtils.clamp((115-alt)/115,0,1);scene.fog.density=(worldIndex?.00102:.00086)+lowAir*(worldIndex?.00028:.00017);speedFXClock+=dt*(2+velocity*8);camBank=THREE.MathUtils.lerp(camBank,bank,1-Math.exp(-dt/.19));camPos.copy(ship.position).addScaledVector(camF,-11.2-velocity*2.5).addScaledVector(worldUp,5.3);camera.position.lerp(camPos,1-Math.exp(-dt/.12));look.copy(ship.position).addScaledVector(camF,42+velocity*11).addScaledVector(worldUp,-12.5);camera.lookAt(look);camera.rotateZ(-camBank*.12);if(velocity>.08){const shake=velocity*.045;camera.translateX(Math.sin(speedFXClock*17)*shake);camera.translateY(Math.sin(speedFXClock*23)*shake*.65)}if(hitKick>.01){camera.translateX(Math.sin(speedFXClock*61)*hitKick*.075);camera.translateY(Math.sin(speedFXClock*47)*hitKick*.05)}camera.fov=THREE.MathUtils.lerp(camera.fov,66+velocity*8.5+THREE.MathUtils.clamp((80-alt)/80,0,1)*2.5+gunKick*1.4+hitKick*.65,1-Math.exp(-dt/.13));camera.updateProjectionMatrix();sky.position.copy(camera.position)}",
"const camF=new THREE.Vector3(),camPos=new THREE.Vector3(),look=new THREE.Vector3(),camRight=new THREE.Vector3();function updateCamera(dt){gunKick*=Math.exp(-dt/.065);hitKick*=Math.exp(-dt/.075);camF.set(0,0,-1).applyQuaternion(ship.quaternion).normalize();const up=worldUp.clone().applyQuaternion(ship.quaternion),bank=Math.atan2(up.x,up.y),pi=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),combatPull=Math.abs(pi)*THREE.MathUtils.smoothstep(Math.abs(bank),.26,.78),alt=Math.max(0,ship.position.y-terrainHeight(ship.position.x,ship.position.z)),velocity=THREE.MathUtils.clamp((speed-124)/56,0,1),lowAir=THREE.MathUtils.clamp((115-alt)/115,0,1);scene.fog.density=(worldIndex?.00102:.00086)+lowAir*(worldIndex?.00028:.00017);speedFXClock+=dt*(2+velocity*8);camBank=THREE.MathUtils.lerp(camBank,bank,1-Math.exp(-dt/.19));camPos.copy(ship.position).addScaledVector(camF,-11.2-velocity*2.5-combatPull*4.2).addScaledVector(worldUp,5.3+combatPull*1.7);camera.position.lerp(camPos,1-Math.exp(-dt/(combatPull>.08?.16:.12)));camRight.crossVectors(camF,worldUp).normalize();look.copy(ship.position).addScaledVector(camF,42+velocity*11+combatPull*5).addScaledVector(worldUp,-12.5+combatPull*2.4).addScaledVector(camRight,-bank*combatPull*3.2);camera.lookAt(look);camera.rotateZ(-camBank*(.12-combatPull*.025));if(velocity>.08){const shake=velocity*.045;camera.translateX(Math.sin(speedFXClock*17)*shake);camera.translateY(Math.sin(speedFXClock*23)*shake*.65)}if(hitKick>.01){camera.translateX(Math.sin(speedFXClock*61)*hitKick*.075);camera.translateY(Math.sin(speedFXClock*47)*hitKick*.05)}camera.fov=THREE.MathUtils.lerp(camera.fov,66+velocity*8.5+combatPull*5.5+THREE.MathUtils.clamp((80-alt)/80,0,1)*2.5+gunKick*1.4+hitKick*.65,1-Math.exp(-dt/(combatPull>.08?.16:.13)));camera.updateProjectionMatrix();sky.position.copy(camera.position)}"
))

for old,new in repls:
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'match count {n} for {old[:80]}')
    s=s.replace(old,new,1)

p.write_text(s)
html=s[s.index('<script type="module">')+len('<script type="module">'):s.index('</script>')]
html=html.replace("import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';",'const THREE={};')
Path('/tmp/emberwing-check.mjs').write_text(html)
subprocess.run(['node','--check','/tmp/emberwing-check.mjs'],check=True)
